baseURL = "https://minimal.eseymour.me/"
languageCode = "en-us"
title = "Edward Seymour"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = "UA-113410660-1"

[params]
    author = "Edward Seymour"
    description = "I'm a web and Android Software Developer in El Paso, Texas"
    githubUsername = "eseymour"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go"]
    copyright = "&copy; Edward Seymour 2018"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

#[[menu.main]]
#    url = "/post/"
#    name = "Posts"
#    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://github.com/eseymour/"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "mailto:mail@edwardseymour.me"
    name = "envelope-o"
    title = "mail@edwardseymour.me"
    weight = 2

[[menu.icon]]
    url = "tel:+01-915-328-5073"
    name = "phone"
    title = "(915) 328-5073"
    weight = 3
