baseurl             = "https://introduction.eseymour.me/"   # Your domain name. Must end with "/"
languageCode        = "en-us"
title               = "Edward Seymour"
theme               = "introduction"
enforce_ssl         = false
builddrafts         = true                         # Include pages with draft status of true
canonifyurls        = true                          # Turns relative urls into absolute urls
# disqusshortname   = "xxx"                         # Enable Disqus for comments
googleAnalytics     = "UA-113410660-1"

[params]
    blogHead        = "Blog"                        # Full name shows on blog post pages
    firstName       = "Edward"                      # First name shows in introduction on main page
    tagLine         = "I'm a web and Android software developer in El Paso, Texas."     # Appears after the introduction
    introHeight     = "fullheight"                       # Input either 'medium' or 'large' or 'fullheight'
    themeStyle      = "light"                       # Choose 'light' or 'dark'
    avatar          = "img/profile.jpg"             # Path to image in static folder eg. img/avatar.png, or comment out to remove
    email           = "edward@edwardseymour.me"      # Shows in contact section, or leave blank to omit
    localTime       = true                          # Show your current local time in contact section
    timeZone        = "America/Denver"              # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    dateForm        = "Jan 2, 2006"
    dateFormFull    = "Mon Jan 2 2006 15:04:05 EST"
    cacheBuster     = false                         # Add the current unix timestamp in query string for cache busting css assets (relevant in development mode)
    description     = "Website Description"         # Max 160 characters show in search results
    faviconFile     = "favicon.ico"
    highlightjs     = true                          # Syntax highlighting
    footerText      = "© Edward Seymour 2018"         # Text to show in footer (overrides default text)
    fadeIn          = false                         # Turn on/off the fade-in effect

    showBlog            = false                      # Show Blog section on home page
    showProjects        = true                      # Show Projects section on home page
    projectColumns      = "3"                       # Choose "2" or "3" columns for projects section
    placeHolderimg      = "/img/workday.jpg"        # For Projects without image
    showAllPosts        = false                     # Set 'true' to list all posts on home page, or set 'false' to link to separate blog list page
    showLatest          = true                      # Show latest blog post summary
    shareButtons        = true                      # On post pages, show share this social buttons

    # Share buttons
    shareTwitter        = true
    shareFacebook       = true
    sharePinterest      = false
    shareGooglePlus     = true

# Social icons appear in introduction and contact section. Add as many more as you like.
# Find icon names here: http://fontawesome.io/cheatsheet/

[[params.social]]
    url = "https://github.com/eseymour/"
    icon = "github"
